# Generated by Django 3.0.9 on 2022-06-10 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmallClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('website', models.CharField(max_length=250)),
                ('point_of_contact', models.EmailField(max_length=250, unique=True)),
                ('profile_pic', models.ImageField(upload_to='uploads/%Y/%m/%d/')),
                ('due_date', models.DateField()),
                ('date_joined', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
