# Generated by Django 3.0.9 on 2022-06-10 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smallclient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smallclient',
            name='goal_choices',
            field=models.CharField(choices=[('CPA', 'CPA'), ('Impressions', 'Impressions'), ('Downloads', 'Downloads'), ('Installs', 'Installs'), ('Purchase', 'Purchase')], default='CPA', max_length=50),
        ),
    ]
